### ISSUE TITLE
bottom navigation

### ISSUE THREAD

**Issue by PIYUJIN** [KUSITMS-HDmedi-A/FE#1]
## Description
메인 화면 bottom navigation
- 홈
- 약관리
- 약검색
- 자가진단
- 마이페이지

## TODO
- [x] build.gradle 의존성 추가
- [x] 메인 Fragment 생성
- [x] Navigation Graph 생성
- [x] Menu 생성
- [x] selector, color 생성
- [x] MainActivity 설정
  - fragment
  - bottomnavigation
